version: '3.8'

services:
  app:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URI=mongodb://mongo:27017/bsg
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    container_name: bsg-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none

volumes:
  mongo-data:
